name: netlify

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: run netlify
      run: |
        pip install sphinx
        sphinx-build ./docs ./_build
        git add .
        git commit -am "initial commit"
        git push origin main

